---
abstract: 'A module for you'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Devel::CheckLib: 0.4
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Devel::CheckLib: 0.4
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MySQL::BinLog
name: MySQL-BinLog
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Scalar::Util: 1.14
  XSLoader: 0.02
  parent: 0.221
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
